### PR TITLE
Php markdown extra

### PR DESCRIPTION
**Pull request by jrsinclair**
Dropplets already uses PHP-Markdown. With only a small change it can be made to support all the additional features of [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/). I find the footnotes additions in particular to be extremely useful. This pull request introduces support for PHP-Markdown-Extra.

### CODE REVIEW

**Comment by ArtFaks** [comment]
Hi, please why this pull request not pulled? 
This would be a great improvement i think!
Markdown extra offers many possibilities.

**Comment by benlk** [comment]
The pull request isn't pulled because the maintainers have pretty much stopped maintaining the project. 

In its current state, it has merge conflicts that would need to be resolved before merging.

This pull request also mingles two unrelated features: Markdown Extra and a change to the avatars service. Those should be split into separate pull requests.

**Comment by ArtFaks** [comment]
OK, thanks for fast reply. I'll try to see from where comes the conflict and I would surely be an another pull request if I succeeds.

**Comment by johnroper100** [comment]
Can you resolve the conflicts?

**Comment by johnroper100** [comment]
@jrsinclair @ArtFaks @benlk Could one of you update this pull request?

**Comment by benlk** [comment]
Sure, I'll take a hack at it. It would be better as a separate pull request, though.

**Pull request merged**
