### PR TITLE
Added New Feature: Author Pages

### PR DESCRIPTION
**Pull request by swaroopsm**
Hi,
This features adds author pages to a website.
Author files are named as author_name.yml and are uploaded the web interface. 

In your markdown posts, you can add the <author_handle> as the author.

### CODE REVIEW

**Comment by johnroper100** [comment]
Can you update this to work with the latest version?

**Comment by swaroopsm** [comment]
@johnroper100 I have updated it. Looks like there is an minimalistic author feature that was added. Saw the `$post_author` variable in the templates. I have removed it since my PR, IMHO adds a little advanced author feature.

**Comment by johnroper100** [comment]
The author page on simple and all other themes are coming up blank. Fresh new install.

**Comment by swaroopsm** [comment]
@johnroper100 Will have a look at it.

**Comment by swaroopsm** [comment]
@johnroper100 Looks like even the `categories` page doesn't seem to work as expected. Could you please check and let let me know as well?

**Comment by johnroper100** [comment]
The categories page works fine for me.

**Pull request merged**
