### PR TITLE
Change Need Some Help? functionality to direct to GitHub

### PR DESCRIPTION
**Pull request by semioticrobotic**
The "Need Some Help?" feature on the toolbar should direct users to GitHub, not send an email to the project creator.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Updated to open help in new window/tab.

**Comment by semioticrobotic** [comment]
Believe it or not, that was my first-ever accepted software patch, trivial as it was. Thanks, @johnroper100!

**Comment by johnroper100** [comment]
No problem!

**Comment by semioticrobotic** [comment]
I'm interested in helping with #412, if I can.

**Comment by johnroper100** [comment]
You can do anything you want.

**Comment by semioticrobotic** [comment]
That is good to know, but in this case I can't determine the source of the error and need some help troubleshooting it.

**Pull request merged**
